// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("OrderItem")]
public partial class OrderItem
{
    [Key]
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? OrderId { get; set; }

    public int? Ouantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    [JsonIgnore]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    [JsonIgnore]
    public virtual Product Product { get; set; }
}