// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    public double? Price { get; set; }

    [Column("ImageURL")]
    public string ImageUrl { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    [JsonIgnore]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    [JsonIgnore]

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}